version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=your_secret_key_here
      - DATABASE_URL=postgresql://quizuser:quizpass@db/quizmaster
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=quizuser
      - POSTGRES_PASSWORD=quizpass
      - POSTGRES_DB=quizmaster
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: